/*
Project: fygemu
Authors: hirakana@kf
*/
{
    let i;
    const 
    
    seed = globalThis.__pp_seed ?? (() => i = 0),
    next = globalThis.__pp_next ?? (() => i++),

    _ = {

        /* Emulator */
        $FlDay: 0x1000000n,
        $FlNight: 0x1000001n,

        $StMin: seed(),
        $StIpMulN: next(), $StIpAddN: next(),
        $StApSetL: next(), $StApSetR: next(),
        $StBpAtkL: next(), $StBpAtkR: next(),
        $StBpCrtL: next(), $StBpCrtR: next(),
        $StBpSklL: next(), $StBpSklR: next(),
        $StBpDefL: next(), $StBpDefR: next(),
        $StBpPowL: next(), $StBpPowR: next(),
        $StBpDmgL: next(), $StBpDmgR: next(),
        $StCpSetL: next(), $StCpSetR: next(),
        $StDpSetL: next(), $StDpSetR: next(),
        $StEpSetL: next(), $StEpSetR: next(),
        $StMax: next(),

        /* Client */
        $CoMin: seed(),
        $CoError: next(),
        $CoSysModal: next(),
        $CoSysReset: next(),
        $CoSysLang: next(),
        $CoSysPage: next(),
        $CoSysPay: next(),
        $CoSysGot: next(),
        $CoSysUsr: next(),
        $CoSysGem: next(),
        $CoSysRank: next(),
        $CoIndexReset: next(),
        $CoIndexSet: next(),
        $CoIndexUsr: next(),
        $CoPkReset: next(),
        $CoPkInit: next(),
        $CoPkFight: next(),
        $CoPkProg: next(),
        $CoPkFuel: next(),
        $CoPkDrug: next(),
        $CoPkLog: next(),
        $CoEquipReset: next(),
        $CoEquipInit: next(),
        $CoEquipGem: next(),
        $CoEquipAcc: next(),
        $CoEquipAcd: next(),
        $CoEquipEcc: next(),
        $CoEquipEcd: next(),
        $CoEquipFcc: next(),
        $CoEquipFcd: next(),
        $CoEquipUsr: next(),
        $CoEquipGrow: next(),
        $CoEquipFight: next(),
        $CoEquipAura: next(),
        $CoEquipView: next(),
        $CoEquipEdit: next(),
        $CoWishReset: next(),
        $CoWishInit: next(),
        $CoWishSet: next(),
        $CoGiftReset: next(),
        $CoGiftInit: next(),
        $CoGiftData: next(),
        $CoGiftFlip: next(),
        $CoShopReset: next(),
        $CoShopInit: next(),
        $CoShopUsr: next(),
        $CoShopEnable: next(),
        $CoDataVer: next(),
        $CoGmArena: next(),
        $CoGmUnit: next(),
        $CoGmActor: next(),
        $CoGmEquip: next(),
        $CoGmBattle: next(),
        $CoGmRoller: next(),
        $CoGmDl: next(),
        $CoMax: next(),

        /* Server */
        $SoMin: seed(),
        $SoIdIn: next(),
        $SoIdUp: next(),
        $SoIdOut: next(),
        $SoIdName: next(),
        $SoIdPass: next(),
        $SoIdDaily: next(),
        $SoPkPvP: next(),
        $SoPkPvE: next(),
        $SoPkPvB: next(),
        $SoPkGain: next(),
        $SoPkDrug: next(),
        $SoAcFgt: next(),
        $SoAcSet: next(),
        $SoAcExp: next(),
        $SoAcElt: next(),
        $SoAcBrk: next(),
        $SoAcSpw: next(),
        $SoEcBrk: next(),
        $SoEcFrg: next(),
        $SoEcCrf: next(),
        $SoEcSml: next(),
        $SoFcBrk: next(),
        $SoFcFrg: next(),
        $SoGcMine: next(),
        $SoWpDrop: next(),
        $SoGpFlip: next(),
        $SoScBack: next(),
        $SoScItem: next(),
        $SoScCoin: next(),
        $SoRpLoad: next(),
        $SoRpSave: next(),
        $SoGmArena: next(),
        $SoGmUnit: next(),
        $SoGmActor: next(),
        $SoGmEquip: next(),
        $SoGmBattle: next(),
        $SoGmRoll: next(),
        $SoGmVipSet: next(),
        $SoGmRankSet: next(),
        $SoGmProgSet: next(),
        $SoGmFuelSet: next(),
        $SoGmCfgEmu: next(),
        $SoGmCfgSvc: next(),
        $SoGmCfgUsr: next(),
        $SoGmCfgRes: next(),
        $SoDataLdr: next(),
        $SoMax: next(),

        /* Server Connection Type */
        $SvcLocal: "L",
        $SvcRemote: "R",

        /* Server Name */
        $SvcAuth: "auth",
        $SvcData: "data",
        $SvcGame: "game",

        /* Data Server */
        $DsEmuUpdate: "emu",
        $DsSysUpdate: "sys",

        /* Callback */
        $CbMin: seed(),
        $CbResolved: next(),
        $CbRejected: next(),
        $CbMax: next(),

        /* Battle Message */
        $BmMin: seed(),
        $BmStat: next(),
        $BmAct: next(),
        $BmHpot: next(),
        $BmSpot: next(),
        $BmArt1: next(),
        $BmArt2: next(),
        $BmArt3: next(),
        $BmAura: next(),
        $BmArt1Ex: next(),
        $BmArt2Ex: next(),
        $BmArt3Ex: next(),
        $BmMax: next(),

        /* Message */
        $MsgMin: seed(),
        
        $MsgMetaTitle: next(),
        $MsgMetaKeywords: next(),
        $MsgMetaDescription: next(),

        $MsgFygRank: next(),
        $MsgFygLevel: next(),
        $MsgFygPk: next(),
        $MsgFygEquip: next(),
        $MsgFygWish: next(),
        $MsgFygBeach: next(),
        $MsgFygGift: next(),
        $MsgFygShop: next(),
        $MsgFygSvc: next(),
        $MsgFygLogout: next(),
        $MsgFygIndex: next(),
        $MsgFygStats: next(),
        $MsgFygByebye: next(),

        $MsgNameId: next(),
        $MsgNamePw: next(),
        $MsgNameRank: next(),
        $MsgNameProg: next(),
        $MsgNameFuel: next(),
        $MsgNameRecover: next(),
        $MsgNamePveLv: next(),
        $MsgNameGmBattle: next(),
        $MsgNameGmRoller: next(),
        $MsgNameGmLoader: next(),
        $MsgNamePkButton1: next(),
        $MsgNamePkButton2: next(),
        $MsgNamePkButton3: next(),
        $MsgNamePkButton4: next(),
        $MsgNameBoard: next(),
        $MsgNameConfig: next(),
        $MsgNameOutput: next(),
        $MsgNameUser: next(),
        $MsgNameCard: next(),
        $MsgNameEquip: next(),
        $MsgNameAura: next(),
        $MsgNameWish: next(),
        $MsgNameAmulet: next(),
        $MsgNameGems: next(),
        $MsgNameDice: next(),
        $MsgNameStats: next(),
        $MsgNameStatus: next(),
        $MsgNameImport: next(),
        $MsgNameExport: next(),
        $MsgNameCreate: next(),
        $MsgNameEditor: next(),
        $MsgNameRemove: next(),
        $MsgNameConfirm: next(),
        $MsgNameClose: next(),
        $MsgNameManual: next(),
        $MsgNameLogin: next(),
        $MsgNameSignup: next(),
        $MsgNameRecord: next(),
        $MsgNameRecordNum: next(),
        $MsgNameRecordPvE: next(),
        $MsgNameRecordPvP: next(),
        $MsgNameRecordPvELv: next(),
        $MsgNameRecordPvPLv: next(),
        $MsgNameRecordTable: next(),
        $MsgNameChange: next(),
        $MsgNameRename: next(),
        $MsgNameRepass: next(),
        $MsgNameSubmit: next(),
        $MsgNameFightSquad: next(),
        $MsgNameActorStock: next(),
        $MsgNameEquipStock: next(),
        $MsgNameFruitStock: next(),
        $MsgNameEquipAmulet: next(),
        $MsgNameEquipSet: next(),
        $MsgNameEquipBreak: next(),
        $MsgNameEquipSmelt: next(),
        $MsgNameEquipForge: next(),
        $MsgNameAuraCommit: next(),
        $MsgNameCraft: next(),
        $MsgNameCraftUsual: next(),
        $MsgNameCraftSuper: next(),
        $MsgNameSpawn: next(),
        $MsgNameSpawnUsual: next(),
        $MsgNameSpawnSuper: next(),
        $MsgNameAmass: next(),
        $MsgNameEditLevel: next(),
        $MsgNameEditTrait: next(),
        $MsgNameEditSkill: next(),
        $MsgNameEditBuild: next(),
        $MsgNameEditGrowth: next(),
        $MsgNameEditFeed: next(),
        $MsgNameEditPointFree: next(),
        $MsgNameEditPointUsed: next(),
        $MsgNameEditPointMax: next(),
        $MsgNameEditCommit: next(),
        $MsgNameEnlight: next(),
        $MsgNameMax: next(),
        $MsgNameSize: next(),
        $MsgNameSort: next(),
        $MsgNameSortID: next(),
        $MsgNameSortKB: next(),
        $MsgNameSortKL: next(),
        $MsgNameSortPB: next(),
        $MsgNameSortPL: next(),
        $MsgNameSortMB: next(),
        $MsgNameSortML: next(),
        $MsgNameWishPool: next(),
        $MsgNameWishBtn: next(),
        $MsgNameBeach: next(),
        $MsgNameGiftPool: next(),
        $MsgNameGiftTotal: next(),
        $MsgNameGiftBase: next(),
        $MsgNameShopUpdate: next(),
        $MsgNameShopVip: next(),
        $MsgNameShopDice: next(),
        $MsgNameShopBuy: next(),
        $MsgNameShopBuyBtn: next(),
        $MsgNameGmLoad: next(),
        $MsgNameGmSave: next(),
        $MsgNameGmEmu: next(),
        $MsgNameGmSvc: next(),
        $MsgNameGmUsr: next(),
        $MsgNameGmRes: next(),

        $MsgDescGmBattle: next(),
        $MsgDescGmLoader: next(),
        $MsgDescGmRoller: next(),
        $MsgDescPkButton1: next(),
        $MsgDescPkButton2: next(),
        $MsgDescPkButton3: next(),
        $MsgDescPkButton4: next(),
        $MsgDescPKWinner: next(),
        $MsgDescPKDraw: next(),
        $MsgDescPKRoundOver: next(),
        $MsgDescManPowerP: next(),
        $MsgDescManPowerM: next(),
        $MsgDescManPowerA: next(),
        $MsgDescManDamageH: next(),
        $MsgDescManDamageS: next(),
        $MsgDescManRecoverH: next(),
        $MsgDescManRecoverS: next(),
        $MsgDescManual: next(),
        $MsgDescLogin: next(),
        $MsgDescSignup: next(),
        $MsgDescRename: next(),
        $MsgDescRepass: next(),
        $MsgDescCraft: next(),
        $MsgDescSpawn: next(),
        $MsgDescAmass: next(),
        $MsgDescWishPool: next(),
        $MsgDescEditLevel: next(),
        $MsgDescEditTrait: next(),
        $MsgDescEditSkill: next(),
        $MsgDescEditBuild: next(),
        $MsgDescEditGrowth: next(),
        $MsgDescEditFeed: next(),
        $MsgDescEnlight: next(),

        $MsgAttrIsPVE: next(),
        $MsgAttrHpMax: next(),
        $MsgAttrSdMax: next(),
        $MsgAttrSpd: next(),
        $MsgAttrPowP: next(),
        $MsgAttrPowM: next(),
        $MsgAttrAtkP: next(),
        $MsgAttrAtkM: next(),
        $MsgAttrDefP: next(),
        $MsgAttrDefM: next(),

        $MsgActCrt: next(),
        $MsgActRfl: next(),
        $MsgActEc2202: next(),
        $MsgActAc3008P: next(),
        $MsgActAc3008M: next(),
        $MsgActAc3008A: next(),
        $MsgActHpPot: next(),
        $MsgActSdPot: next(),
        $MsgStatusPrefix: next(),
        $MsgStatusSuffix: next(),
        $MsgSkillPrefix: next(),
        $MsgSkillSuffix: next(),
        $MsgAuraPrefix: next(),
        $MsgAuraSuffix: next(),

        $MsgPreSVip: next(),
        $MsgPreBVip: next(),
        $MsgPreLevel: next(),
        $MsgPreTrait: next(),
        $MsgPreSkill: next(),
        $MsgPreBuild: next(),
        $MsgPreFlair: next(),
        $MsgPreStatPoint: next(),
        $MsgPreAuraPoint: next(),
        $MsgPreAuraCost: next(),
        $MsgPreExp: next(),
        $MsgPreAuraH3: next(),
        $MsgPreRecordWin: next(),
        $MsgPreRecordLose: next(),

        $MsgMidAuraH3: next(),

        $MsgSufSVip: next(),
        $MsgSufBVip: next(),
        $MsgSufLevel: next(),
        $MsgSufTrait: next(),
        $MsgSufSkill: next(),
        $MsgSufBuild: next(),
        $MsgSufFlair: next(),
        $MsgSufStatPoint: next(),
        $MsgSufAuraPoint: next(),
        $MsgSufAuraCost: next(),
        $MsgSufExp: next(),
        $MsgSufAuraH3: next(),
        $MsgSufRecordWin: next(),
        $MsgSufRecordLose: next(),

        $MsgHintDaily: next(),
        $MsgHintItGet: next(),
        $MsgHintItUse: next(),
        $MsgHintItBuy: next(),
        $MsgHintAcGet: next(),
        $MsgHintAcUpd: next(),
        $MsgHintAcUse: next(),
        $MsgHintAcElt: next(),
        $MsgHintEcGet: next(),
        $MsgHintEcUpd: next(),
        $MsgHintEcUse: next(),
        $MsgHintFcGet: next(),
        $MsgHintFcUpd: next(),
        $MsgHintFcUse: next(),
        $MsgHintEditLevel: next(),
        $MsgHintEditFlair: next(),

        $MsgMax: next(),

        /* Net Data */
        $NetMin: seed(),
        $NetDataDate: next(),
        $NetActorBst: next(),
        $NetActorPst: next(),
        $NetEquipPst: next(),

        $NetItemMax: next(),
        $NetRankMax: next(),
        $NetTrailMin: next(),
        $NetDrugCost: next(),
        $NetEquipLimit: next(),
        $NetFruitLimit: next(),
        $NetCraftItems: next(),
        $NetSpawnItems: next(),
        $NetAmassItems: next(),
        $NetActorExp: next(),
        $NetActorElt: next(), 
        $NetEquipForgeCost: next(),
        $NetEquipForgeMul: next(),
        $NetEquipForgeCap: next(),
        $NetFruitForgeCost: next(),
        $NetFruitForgeMul: next(),
        $NetFruitForgeCap: next(),
        $NetAuraCost: next(),
        $NetWishLimit: next(),
        $NetWishDaily: next(),
        $NetWishCost: next(),
        $NetGiftCost: next(),
        $NetShopItem: next(),
        $NetShopBack: next(),

        $Empty: 0xffffffff
        
    }

    if (globalThis.window) { Object.assign(globalThis, _); }
    else { module.exports = _; }
}