/*
Project: fygemu
Authors: hirakana@kf
*/
{
    let i;
    const _ = {

        /* Emulator */
        $StMin: i = 0,
        $StIpMulN: i++, $StIpAddN: i++,
        $StApSetL: i++, $StApSetR: i++,
        $StBpAtkL: i++, $StBpAtkR: i++,
        $StBpCrtL: i++, $StBpCrtR: i++,
        $StBpSklL: i++, $StBpSklR: i++,
        $StBpDefL: i++, $StBpDefR: i++,
        $StBpPowL: i++, $StBpPowR: i++,
        $StBpDmgL: i++, $StBpDmgR: i++,
        $StCpSetL: i++, $StCpSetR: i++,
        $StDpSetL: i++, $StDpSetR: i++,
        $StEpSetL: i++, $StEpSetR: i++,
        $StMax: i,

        /* Client */
        $CoMin: i = 0,
        $CoError: i++,
        $CoSysReset: i++,
        $CoSysLang: i++,
        $CoSysPage: i++,
        $CoSysPay: i++,
        $CoSysUsr: i++,
        $CoSysGem: i++,
        $CoSysRank: i++,
        $CoIndexReset: i++,
        $CoIndexSet: i++,
        $CoPkReset: i++,
        $CoPkFight: i++,
        $CoPkRank: i++,
        $CoPkProg: i++,
        $CoPkFuel: i++,
        $CoPkCost: i++,
        $CoPkDrug: i++,
        $CoPkData: i++,
        $CoPkLog: i++,
        $CoEquipReset: i++,
        $CoEquipData: i++,
        $CoEquipCost: i++,
        $CoEquipGem: i++,
        $CoEquipAcc: i++,
        $CoEquipAcd: i++,
        $CoEquipEcc: i++,
        $CoEquipEcd: i++,
        $CoEquipFcc: i++,
        $CoEquipFcd: i++,
        $CoEquipUsr: i++,
        $CoEquipGrow: i++,
        $CoEquipFight: i++,
        $CoEquipAura: i++,
        $CoEquipView: i++,
        $CoEquipEdit: i++,
        $CoWishReset: i++,
        $CoWishSet: i++,
        $CoWishMax: i++,
        $CoWishCost: i++,
        $CoGiftReset: i++,
        $CoGiftData: i++,
        $CoGiftFlip: i++,
        $CoGiftCost: i++,
        $CoShopReset: i++,
        $CoShopSet: i++,
        $CoShopUsr: i++,
        $CoShopEnable: i++,
        $CoGmArena: i++,
        $CoGmUnit: i++,
        $CoGmActor: i++,
        $CoGmEquip: i++,
        $CoGmBattle: i++,
        $CoGmRoller: i++,
        $CoGmDl: i++,
        $CoMax: i,

        /* Server */
        $SoMin: i = 0,
        $SoIdIn: i++,
        $SoIdUp: i++,
        $SoIdOut: i++,
        $SoIdName: i++,
        $SoIdPass: i++,
        $SoPkPvP: i++,
        $SoPkPvE: i++,
        $SoPkPvB: i++,
        $SoPkGain: i++,
        $SoPkDrug: i++,
        $SoAcFgt: i++,
        $SoAcSet: i++,
        $SoAcExp: i++,
        $SoAcElt: i++,
        $SoAcBrk: i++,
        $SoAcSpw: i++,
        $SoEcBrk: i++,
        $SoEcCrf: i++,
        $SoEcSml: i++,
        $SoFcBrk: i++,
        $SoFcFrg: i++,
        $SoGcMine: i++,
        $SoWpDrop: i++,
        $SoGpFlip: i++,
        $SoScBack: i++,
        $SoScItem: i++,
        $SoScCoin: i++,
        $SoRpLoad: i++,
        $SoRpSave: i++,
        $SoGmArena: i++,
        $SoGmUnit: i++,
        $SoGmActor: i++,
        $SoGmEquip: i++,
        $SoGmBattle: i++,
        $SoGmRoll: i++,
        $SoGmVipSet: i++,
        $SoGmRankSet: i++,
        $SoGmProgSet: i++,
        $SoGmFuelSet: i++,
        $SoGmCfgEmu: i++,
        $SoGmCfgSvc: i++,
        $SoGmCfgUsr: i++,
        $SoGmCfgRes: i++,
        $SoMax: i,

        /* Callback */
        $CbMin: i = 0,
        $CbResolved: i++,
        $CbRejected: i++,
        $CbMax: i,

        $Empty: 0xffffffff
        
    }

    if (global.window) { Object.assign(global, _); }
    else { module.exports = _; }
}