/*
Project: fygemu
Authors: hirakana@kf
*/
{
    let i;
    const 
    
    seed = globalThis.__pp_seed ?? (() => i = 0),
    next = globalThis.__pp_next ?? (() => i++),

    _ = {

        /* Emulator */
        $FlDay: 0x1000000n,
        $FlNight: 0x1000001n,

        $StMin: seed(),
        $StIpMulN: next(), $StIpAddN: next(),
        $StApSetL: next(), $StApSetR: next(),
        $StBpAtkL: next(), $StBpAtkR: next(),
        $StBpCrtL: next(), $StBpCrtR: next(),
        $StBpSklL: next(), $StBpSklR: next(),
        $StBpDefL: next(), $StBpDefR: next(),
        $StBpPowL: next(), $StBpPowR: next(),
        $StBpDmgL: next(), $StBpDmgR: next(),
        $StCpSetL: next(), $StCpSetR: next(),
        $StDpSetL: next(), $StDpSetR: next(),
        $StEpSetL: next(), $StEpSetR: next(),
        $StMax: next(),

        /* Client */
        $CoMin: seed(),
        $CoError: next(),
        $CoSysModal: next(),
        $CoSysReset: next(),
        $CoSysLang: next(),
        $CoSysPage: next(),
        $CoSysPay: next(),
        $CoSysGot: next(),
        $CoSysUsr: next(),
        $CoSysGem: next(),
        $CoSysRank: next(),
        $CoIndexReset: next(),
        $CoIndexSet: next(),
        $CoIndexUsr: next(),
        $CoPkReset: next(),
        $CoPkInit: next(),
        $CoPkFight: next(),
        $CoPkProg: next(),
        $CoPkFuel: next(),
        $CoPkDrug: next(),
        $CoPkLog: next(),
        $CoEquipReset: next(),
        $CoEquipInit: next(),
        $CoEquipGem: next(),
        $CoEquipAcc: next(),
        $CoEquipAcd: next(),
        $CoEquipEcc: next(),
        $CoEquipEcd: next(),
        $CoEquipFcc: next(),
        $CoEquipFcd: next(),
        $CoEquipUsr: next(),
        $CoEquipGrow: next(),
        $CoEquipFight: next(),
        $CoEquipAura: next(),
        $CoEquipView: next(),
        $CoEquipEdit: next(),
        $CoWishReset: next(),
        $CoWishInit: next(),
        $CoWishSet: next(),
        $CoGiftReset: next(),
        $CoGiftInit: next(),
        $CoGiftData: next(),
        $CoGiftFlip: next(),
        $CoShopReset: next(),
        $CoShopInit: next(),
        $CoShopUsr: next(),
        $CoShopEnable: next(),
        $CoDataVer: next(),
        $CoGmArena: next(),
        $CoGmUnit: next(),
        $CoGmActor: next(),
        $CoGmEquip: next(),
        $CoGmBattle: next(),
        $CoGmRoller: next(),
        $CoGmDl: next(),
        $CoMax: next(),

        /* Server */
        $SoMin: seed(),
        $SoIdIn: next(),
        $SoIdUp: next(),
        $SoIdOut: next(),
        $SoIdName: next(),
        $SoIdPass: next(),
        $SoIdDaily: next(),
        $SoPkPvP: next(),
        $SoPkPvE: next(),
        $SoPkPvB: next(),
        $SoPkGain: next(),
        $SoPkDrug: next(),
        $SoAcFgt: next(),
        $SoAcSet: next(),
        $SoAcExp: next(),
        $SoAcElt: next(),
        $SoAcBrk: next(),
        $SoAcSpw: next(),
        $SoEcBrk: next(),
        $SoEcFrg: next(),
        $SoEcCrf: next(),
        $SoEcSml: next(),
        $SoFcBrk: next(),
        $SoFcFrg: next(),
        $SoGcMine: next(),
        $SoWpDrop: next(),
        $SoGpFlip: next(),
        $SoScBack: next(),
        $SoScItem: next(),
        $SoScCoin: next(),
        $SoRpLoad: next(),
        $SoRpSave: next(),
        $SoGmArena: next(),
        $SoGmUnit: next(),
        $SoGmActor: next(),
        $SoGmEquip: next(),
        $SoGmBattle: next(),
        $SoGmRoll: next(),
        $SoGmVipSet: next(),
        $SoGmRankSet: next(),
        $SoGmProgSet: next(),
        $SoGmFuelSet: next(),
        $SoGmCfgEmu: next(),
        $SoGmCfgSvc: next(),
        $SoGmCfgUsr: next(),
        $SoGmCfgRes: next(),
        $SoDataLdr: next(),
        $SoMax: next(),

        /* Server Connection Type */
        $SvcLocal: "L",
        $SvcRemote: "R",

        /* Server Name */
        $SvcAuth: "auth",
        $SvcData: "data",
        $SvcGame: "game",

        /* Data Server */
        $DsEmuUpdate: "emu",
        $DsSysUpdate: "sys",

        /* Callback */
        $CbMin: seed(),
        $CbResolved: next(),
        $CbRejected: next(),
        $CbMax: next(),

        /* Battle Message */
        $BmMin: seed(),
        $BmStat: next(),
        $BmAct: next(),
        $BmHpot: next(),
        $BmSpot: next(),
        $BmSkl: next(),
        $BmSklEx: next(),
        $BmMax: next(),

        /* Message */
        $MsgMin: seed(),
        
        $MsgMetaTitle: next(),
        $MsgMetaKeywords: next(),
        $MsgMetaDescription: next(),

        $MsgFygRank: next(),
        $MsgFygLevel: next(),
        $MsgFygPk: next(),
        $MsgFygEquip: next(),
        $MsgFygWish: next(),
        $MsgFygBeach: next(),
        $MsgFygGift: next(),
        $MsgFygShop: next(),
        $MsgFygSvc: next(),
        $MsgFygLogout: next(),
        $MsgFygIndex: next(),
        $MsgFygStats: next(),
        $MsgFygByebye: next(),

        $MsgNameId: next(),
        $MsgNamePw: next(),
        $MsgNameRank: next(),
        $MsgNameProg: next(),
        $MsgNameFuel: next(),
        $MsgNameRecover: next(),
        $MsgNamePveLv: next(),
        $MsgNameGmBattle: next(),
        $MsgNameGmRoller: next(),
        $MsgNameGmLoader: next(),
        $MsgNamePkButton1: next(),
        $MsgNamePkButton2: next(),
        $MsgNamePkButton3: next(),
        $MsgNamePkButton4: next(),
        $MsgNameBoard: next(),
        $MsgNameConfig: next(),
        $MsgNameOutput: next(),
        $MsgNameUser: next(),
        $MsgNameCard: next(),
        $MsgNameEquip: next(),
        $MsgNameAura: next(),
        $MsgNameWish: next(),
        $MsgNameAmulet: next(),
        $MsgNameGems: next(),
        $MsgNameDice: next(),
        $MsgNameStats: next(),
        $MsgNameStatus: next(),
        $MsgNameImport: next(),
        $MsgNameExport: next(),
        $MsgNameCreate: next(),
        $MsgNameEditor: next(),
        $MsgNameRemove: next(),
        $MsgNameConfirm: next(),
        $MsgNameClose: next(),
        $MsgNameManual: next(),
        $MsgNameLogin: next(),
        $MsgNameSignup: next(),
        $MsgNameRecord: next(),
        $MsgNameRecordNum: next(),
        $MsgNameRecordPvE: next(),
        $MsgNameRecordPvP: next(),
        $MsgNameRecordPvELv: next(),
        $MsgNameRecordPvPLv: next(),
        $MsgNameRecordTable: next(),
        $MsgNameChange: next(),
        $MsgNameRename: next(),
        $MsgNameRepass: next(),
        $MsgNameSubmit: next(),
        $MsgNameFightSquad: next(),
        $MsgNameActorStock: next(),
        $MsgNameEquipStock: next(),
        $MsgNameFruitStock: next(),
        $MsgNameEquipAmulet: next(),
        $MsgNameEquipSet: next(),
        $MsgNameEquipBreak: next(),
        $MsgNameEquipSmelt: next(),
        $MsgNameEquipForge: next(),
        $MsgNameAuraCommit: next(),
        $MsgNameCraft: next(),
        $MsgNameCraftUsual: next(),
        $MsgNameCraftSuper: next(),
        $MsgNameSpawn: next(),
        $MsgNameSpawnUsual: next(),
        $MsgNameSpawnSuper: next(),
        $MsgNameAmass: next(),
        $MsgNameEditLevel: next(),
        $MsgNameEditTrait: next(),
        $MsgNameEditSkill: next(),
        $MsgNameEditBuild: next(),
        $MsgNameEditGrowth: next(),
        $MsgNameEditFeed: next(),
        $MsgNameEditPointFree: next(),
        $MsgNameEditPointUsed: next(),
        $MsgNameEditPointMax: next(),
        $MsgNameEditCommit: next(),
        $MsgNameEnlight: next(),
        $MsgNameMax: next(),
        $MsgNameSize: next(),
        $MsgNameSort: next(),
        $MsgNameSortID: next(),
        $MsgNameSortKB: next(),
        $MsgNameSortKL: next(),
        $MsgNameSortPB: next(),
        $MsgNameSortPL: next(),
        $MsgNameSortMB: next(),
        $MsgNameSortML: next(),
        $MsgNameWishPool: next(),
        $MsgNameWishBtn: next(),
        $MsgNameBeach: next(),
        $MsgNameGiftPool: next(),
        $MsgNameGiftTotal: next(),
        $MsgNameGiftBase: next(),
        $MsgNameShopUpdate: next(),
        $MsgNameShopVip: next(),
        $MsgNameShopDice: next(),
        $MsgNameShopBuy: next(),
        $MsgNameShopBuyBtn: next(),
        $MsgNameGmLoad: next(),
        $MsgNameGmSave: next(),
        $MsgNameGmEmu: next(),
        $MsgNameGmSvc: next(),
        $MsgNameGmUsr: next(),
        $MsgNameGmRes: next(),

        $MsgDescGmBattle: next(),
        $MsgDescGmLoader: next(),
        $MsgDescGmRoller: next(),
        $MsgDescPkButton1: next(),
        $MsgDescPkButton2: next(),
        $MsgDescPkButton3: next(),
        $MsgDescPkButton4: next(),
        $MsgDescPKWinner: next(),
        $MsgDescPKDraw: next(),
        $MsgDescPKRoundOver: next(),
        $MsgDescManPowerP: next(),
        $MsgDescManPowerM: next(),
        $MsgDescManPowerA: next(),
        $MsgDescManDamageH: next(),
        $MsgDescManDamageS: next(),
        $MsgDescManRecoverH: next(),
        $MsgDescManRecoverS: next(),
        $MsgDescManual: next(),
        $MsgDescLogin: next(),
        $MsgDescSignup: next(),
        $MsgDescRename: next(),
        $MsgDescRepass: next(),
        $MsgDescCraft: next(),
        $MsgDescSpawn: next(),
        $MsgDescAmass: next(),
        $MsgDescWishPool: next(),
        $MsgDescEditLevel: next(),
        $MsgDescEditTrait: next(),
        $MsgDescEditSkill: next(),
        $MsgDescEditBuild: next(),
        $MsgDescEditGrowth: next(),
        $MsgDescEditFeed: next(),
        $MsgDescEnlight: next(),

        $MsgAttrIsPVE: next(),
        $MsgAttrHpMax: next(),
        $MsgAttrSdMax: next(),
        $MsgAttrSpd: next(),
        $MsgAttrPowP: next(),
        $MsgAttrPowM: next(),
        $MsgAttrAtkP: next(),
        $MsgAttrAtkM: next(),
        $MsgAttrDefP: next(),
        $MsgAttrDefM: next(),

        $MsgActCrt: next(),
        $MsgActRfl: next(),
        $MsgActEc2202: next(),
        $MsgActAc3008P: next(),
        $MsgActAc3008M: next(),
        $MsgActAc3008A: next(),
        $MsgActHpPot: next(),
        $MsgActSdPot: next(),
        $MsgStatusPrefix: next(),
        $MsgStatusSuffix: next(),
        $MsgSkillPrefix: next(),
        $MsgSkillSuffix: next(),
        $MsgAuraPrefix: next(),
        $MsgAuraSuffix: next(),

        $MsgPreSVip: next(),
        $MsgPreBVip: next(),
        $MsgPreLevel: next(),
        $MsgPreTrait: next(),
        $MsgPreSkill: next(),
        $MsgPreBuild: next(),
        $MsgPreFlair: next(),
        $MsgPreStatPoint: next(),
        $MsgPreAuraPoint: next(),
        $MsgPreAuraCost: next(),
        $MsgPreExp: next(),
        $MsgPreAuraH3: next(),
        $MsgPreRecordWin: next(),
        $MsgPreRecordLose: next(),

        $MsgMidAuraH3: next(),

        $MsgSufSVip: next(),
        $MsgSufBVip: next(),
        $MsgSufLevel: next(),
        $MsgSufTrait: next(),
        $MsgSufSkill: next(),
        $MsgSufBuild: next(),
        $MsgSufFlair: next(),
        $MsgSufStatPoint: next(),
        $MsgSufAuraPoint: next(),
        $MsgSufAuraCost: next(),
        $MsgSufExp: next(),
        $MsgSufAuraH3: next(),
        $MsgSufRecordWin: next(),
        $MsgSufRecordLose: next(),

        $MsgHintDaily: next(),
        $MsgHintItGet: next(),
        $MsgHintItUse: next(),
        $MsgHintItBuy: next(),
        $MsgHintAcGet: next(),
        $MsgHintAcUpd: next(),
        $MsgHintAcUse: next(),
        $MsgHintAcElt: next(),
        $MsgHintEcGet: next(),
        $MsgHintEcUpd: next(),
        $MsgHintEcUse: next(),
        $MsgHintFcGet: next(),
        $MsgHintFcUpd: next(),
        $MsgHintFcUse: next(),
        $MsgHintEditLevel: next(),
        $MsgHintEditFlair: next(),

        $MsgMax: next(),

        /* Net Data */
        $NetMin: seed(),
        $NetDataDate: next(),
        $NetActorBst: next(),
        $NetActorPst: next(),
        $NetEquipPst: next(),

        $NetItemMax: next(),
        $NetRankMax: next(),
        $NetTrailMin: next(),
        $NetDrugCost: next(),
        $NetEquipLimit: next(),
        $NetFruitLimit: next(),
        $NetCraftItems: next(),
        $NetSpawnItems: next(),
        $NetAmassItems: next(),
        $NetActorExp: next(),
        $NetActorElt: next(), 
        $NetEquipForgeCost: next(),
        $NetEquipForgeMul: next(),
        $NetEquipForgeCap: next(),
        $NetFruitForgeCost: next(),
        $NetFruitForgeMul: next(),
        $NetFruitForgeCap: next(),
        $NetAuraCost: next(),
        $NetWishLimit: next(),
        $NetWishDaily: next(),
        $NetWishCost: next(),
        $NetGiftCost: next(),
        $NetShopItem: next(),
        $NetShopBack: next(),

        $Empty: 0xffffffff,
        $ActorMystIndex: 3,
        $EquipMystIndex: 0,
        $GmBaseUnit: `{"User":{"3001":0,"3002":0,"3003":0,"3004":0,"3005":0,"3301":0,"3302":0,"3303":0,"3309":0,"3310":0,"name":"","grade":0,"exp":0,"atk":0,"def":0,"coin1":0,"coin2":0,"coin3":0,"svip":0,"bvip":0,"actor":0,"equip":0,"fruit":0,"daily":0,"craft":0,"spawn":0,"amass":0,"wish":0,"gift":0,"shop":0},"Actor":{"K":"0","R":1,"V":0,"L":0,"Q":0,"S":0,"B":0,"F":0,"G":0,"Z":[],"str":0,"agi":0,"int":0,"vit":0,"spr":0,"mnd":0,"p":0},"Equip":[],"Amulet":{"str":0,"agi":0,"int":0,"vit":0,"spr":0,"mnd":0,"pp":0,"pm":0,"pc":0,"ps":0,"rp":0,"rm":0,"rc":0,"rs":0,"ap":0,"am":0,"dp":0,"dm":0,"crt":0,"skl":0,"dod":0,"eva":0,"spd":0,"rec":0,"hp":0,"sd":0,"lch":0,"rfl":0},"Wish":{"ph":0,"ps":0,"a1":0,"a2":0,"a3":0,"pp":0,"pm":0,"hp":0,"sd":0,"sp":0,"ap":0,"am":0,"dp":0,"dm":0},"Aura":[],"Dice":{"L":0,"X":0,"h":0,"a":0,"d":0,"l":0,"r":0,"c":0,"z":0},"Gems":{},"$Flag":[],"$Mode":0,"$HpMaxMul":0,"$HpMaxAdd":0,"$HpHealRat":0,"$HpHealMul":0,"$HpHealAdd":0,"$SdMaxMul":0,"$SdMaxAdd":0,"$SdHealRat":0,"$SdHealMul":0,"$SdHealAdd":0,"$PowMulP":0,"$PowAddP":0,"$PowMulM":0,"$PowAddM":0,"$PowMulA":0,"$PowAddA":0,"$SpdMul":0,"$SpdAdd":0,"$AtkRatP":0,"$AtkMulP":0,"$AtkAddP":0,"$AtkRatM":0,"$AtkMulM":0,"$AtkAddM":0,"$AtkRatC":0,"$AtkMulC":0,"$AtkAddC":0,"$DefRatP":0,"$DefMulP":0,"$DefAddP":0,"$DefRatM":0,"$DefMulM":0,"$DefAddM":0,"$ResMulP":0,"$ResAddP":0,"$ResMulM":0,"$ResAddM":0,"$CrtRat":0,"$SklRat":0,"$SklMul":0,"$SklAdd":0,"$CrtMul":0,"$CrtAdd":0,"$DodRat":0,"$EvaRat":0,"$EvaMul":0,"$EvaAdd":0,"$DodMul":0,"$DodAdd":0,"$LchRat":0,"$RflRat":0,"$Level":0,"$Actor":"0","$Trait":0,"$Skill":0,"$Build":0,"$Growth":0,"$Str":0,"$Agi":0,"$Int":0,"$Vit":0,"$Spr":0,"$Mnd":0,"$Grade":0,"$HndAtk":0,"$HndDef":0,"$PowRatP":0,"$PowRatM":0,"$PowRatC":0,"$PowRatS":0,"$ResRatP":0,"$ResRatM":0,"$ResRatC":0,"$ResRatS":0,"$SpdRat":0,"$RecRat":0,"$HpRat":0,"$SdRat":0,"$LchFix":0,"$RflFix":0,"$CrtFix":0,"$SklFix":0,"$DodFix":0,"$EvaFix":0,"$AtkFixP":0,"$AtkFixM":0,"$DefFixP":0,"$DefFixM":0}`,
        $GmBaseEquip: `{"K":"","L":0,"Q":[],"Z":[],"S":[],"R":1}`
    }

    if (globalThis.window) { Object.assign(globalThis, _); }
    else { module.exports = _; }
}