const gLytJson =
{
    "$": {
        "": ".fyg_head, .fyg_foot",
        "login": ".fyg_login, .fyg_foot",
        "index": ".fyg_head, .fyg_index, .fyg_foot",
        "pk": ".fyg_head, .fyg_pk, .fyg_foot",
        "equip": ".fyg_head, .fyg_equip, .fyg_foot",
        "wish": ".fyg_head, .fyg_wish, .fyg_foot",
        "beach": ".fyg_head, .fyg_beach, .fyg_foot",
        "gift": ".fyg_head, .fyg_gift, .fyg_foot",
        "shop": ".fyg_head, .fyg_shop, .fyg_foot",
        "byebye": ".fyg_byebye, .fyg_foot",
    },
    "pk": {
        "Unit": {
            "mActor": ["nActor"],
            "mLevel": ["nLevel"],
            "mQuality": ["nQuality"],
            "mSkill": ["nSkill"],
            "mGrowth": ["nGrowth"],
            "nHpRat": ["nHpRat"],
            "nHpMax": ["nHpMaxMul", "nHpMaxAdd"],
            "nHpHealRat": ["nHpHealRat"],
            "nHpHealFix": ["nHpHealMul", "nHpHealAdd"],
            "nSdRat": ["nSdRat"],
            "nSdMax": ["nSdMaxMul", "nSdMaxAdd"],
            "nSdHealRat": ["nSdHealRat"],
            "nSdHealFix": ["nSdHealMul", "nSdHealAdd"],
            "nRecRat": ["nRecRat"],
            "nPowRatP": ["nPowRatP"],
            "nPowP": ["nPowMulP", "nPowAddP"],
            "nPowRatM": ["nPowRatM"],
            "nPowM": ["nPowMulM", "nPowAddM"],
            "nPowA": ["nPowMulA", "nPowAddA"],
            "nSpdRat": ["nSpdRat"],
            "nSpd": ["nSpdMul", "nSpdAdd"],
            "nAtkRatP": ["nAtkRatP"],
            "nAtkAddP": ["nAtkMulP", "nAtkAddP"],
            "nAtkRatM": ["nAtkRatM"],
            "nAtkAddM": ["nAtkMulM", "nAtkAddM"],
            "nAtkRatC": ["nAtkRatC"],
            "nAtkAddC": ["nAtkMulC", "nAtkAddC"],
            "nDefRatP": ["nDefRatP", "nDefFixP"],
            "nDefP": ["nDefMulP", "nDefAddP"],
            "nDefRatM": ["nDefRatM", "nDefFixM"],
            "nDefM": ["nDefMulM", "nDefAddM"],
            "nSklRat": ["nSklRat", "nSklFix"],
            "nSklAdd": ["nSklMul", "nSklAdd"],
            "nCrtRat": ["nCrtRat", "nCrtFix"],
            "nCrtAdd": ["nCrtMul", "nCrtAdd"],
            "nEvaRat": ["nEvaRat", "nEvaFix"],
            "nEvaAdd": ["nEvaMul", "nEvaAdd"],
            "nDodRat": ["nDodRat", "nDodFix"],
            "nDodAdd": ["nDodMul", "nDodAdd"],
            "nResP": ["nResMulP", "nResAddP"],
            "nResM": ["nResMulM", "nResAddM"],
            "nLchRat": ["nLchRat", "nLchFix"],
            "nRflRat": ["nRflRat", "nRflFix"],
            "mStr": ["nStr"],
            "mAgi": ["nAgi"],
            "mInt": ["nInt"],
            "mVit": ["nVit"],
            "mSpr": ["nSpr"],
            "mMnd": ["nMnd"]
        },
        "UnitWishs": {
            "mHpPot": "nWishHpPot",
            "mSdPot": "nWishSdPot",
            "mAura101": "nWishAura101",
            "mAura102": "nWishAura102",
            "mAura103": "nWishAura103",
            "mPowBuf": "nWishPowBuf",
            "mLifeBuf": "nWishLifeBuf"
        },
        "EditorActor": {
            "mLevel": "mLevel",
            "mQuality": "mQuality",
            "mSkill": "mSkill",
            "mGrowth": "mGrowth",
            "mStr": "mStr",
            "mAgi": "mAgi",
            "mInt": "mInt",
            "mVit": "mVit",
            "mSpr": "mSpr",
            "mMnd": "mMnd"
        },
        "EditorWishs": {
            "mHpPot": "mHpPot",
            "mSdPot": "mSdPot",
            "mAura101": "mAura101",
            "mAura102": "mAura102",
            "mAura103": "mAura103",
            "mPowBuf": "mPowBuf",
            "mLifeBuf": "mLifeBuf"
        },
        "EditorAmulet": {
            "mAmulStr": "mStr",
            "mAmulAgi": "mAgi",
            "mAmulInt": "mInt",
            "mAmulVit": "mVit",
            "mAmulSpr": "mSpr",
            "mAmulMnd": "mMnd",
            "mAmulPowP": "mPowP",
            "mAmulPowM": "mPowM",
            "mAmulSpd": "mSpd",
            "mAmulRec": "mRec",
            "mAmulHp": "mHp",
            "mAmulSd": "mSd",
            "mAmulLch": "mLch",
            "mAmulRfl": "mRfl",
            "mAmulCrt": "mCrt",
            "mAmulSkl": "mSkl",
            "mAmulDefP": "mDefP",
            "mAmulDefM": "mDefM"
        }
    }
}