const gMsgZzJson = 
{
    "Name": "DEBUG",
    "MetaData": {
        "Title": "fygemu",
        "Keywords": "",
        "Description": ""
    },
    "PanelName": {
        "fygRank": "Rank",
        "fygLevel": "Level",
        "fygCoin1": "Coin1",
        "fygCoin2": "Coin2",
        "fygCoin3": "Coin3",
        "fygPk": "Fight",
        "fygEquip": "Equip",
        "fygWish": "Wish",
        "fygBeach": "Beach",
        "fygGift": "Gift",
        "fygShop": "Shop",
        "fygLogout": "Logout",
        "fygIndex": "Changes",
        "fygByebye": "Byebye",
        "Rank": "Rank",
        "Prog": "Progress",
        "Fuel": "Stamina",
        "Recover": "Refill Stamina to 100",
        "RecoverA": "Confirm (Cost ",
        "RecoverB": " Coins)",
        "NpcStr": "NPC Strength",
        "PkBattle": "Battle Emulation",
        "PkLoader": "Battle Log",
        "PkButton1": "Search for Resources",
        "PkButton2": "Attack Monsters",
        "PkButton3": "Snatch Progress",
        "Config": "Battle Settings",
        "Output": "Battle Logs",
        "Card": "Card Settings",
        "Equip": "Gear Settings",
        "Aura": "Aura Settings",
        "Wish": "Wish Settings",
        "Amulet": "Amulet Settings",
        "Stats": "Stats",
        "Status": "Status",
        "Require": "",
        "Point": "Points",
        "Import": "Import",
        "Export": "Export",
        "Create": "Create",
        "Editor": "Editor",
        "Remove": "Remove",
        "Confirm": "Confirm",
        "Close": "Close",
        "Manual": "Manual"
    },
    "PanelDesc": {
        "PkBattle": "Starts battle with current configuration.",
        "PkLoader": "Loads battle log from a external file.",
        "PkButton1": "Consumes 10 stamina and 3% progress. The reward range is based on the current rank.",
        "PkButton2": "Consumes consumes 5 stamina. Gains 6% progress on victory, losses 1% on failure.",
        "PkButton3": "Consumes 5 stamina. Gains 12% progress on victory, losses 6% on failure.",
        "PKWinner": " wins!",
        "PKRoundOver": "Round over",
        "ManPowerP": "P",
        "ManPowerM": "M",
        "ManPowerA": "A",
        "ManDamageH": "H-",
        "ManDamageS": "S-",
        "ManRecoverH": "H+",
        "ManRecoverS": "S+",
        "Manual": ""
    },
    "AttrName": {
        "mName": "Name"
    },
    "AttrInfo": {
        "mIsPVE": "Enemy",
        "mHpMax": "HP",
        "mSdMax": "SD",
        "mSpd": "SPD",
        "mPowP": "PA",
        "mPowM": "MA",
        "mDefP": "PD",
        "mDefM": "MD"
    },
    "ActUIInfo": {
        "Crt": "CRT",
        "Rfl": "RFL",
        "Equip2202": "MCRT",
        "Art3008": ["-P", "-M", "-A"],
        "HpPot": "PotH",
        "SdPot": "PotS",
        "StatusPrefix": " ",
        "StatusSuffix": "",
        "SkillPrefix": "",
        "SkillSuffix": "",
        "AuraPrefix": "",
        "AuraSuffix": ""
    },
    "ActorName": {
        "0": "NONE",
        "3000": "WU",
        "3001": "MO",
        "3002": "LIN",
        "3003": "AI",
        "3004": "MENG",
        "3005": "WEI",
        "3006": "YI",
        "3007": "MING",
        "3008": "MIN",
        "3009": "XI",
        "3901": "MU",
        "3902": "ZHU",
        "3903": "DENG",
        "3904": "SHOU",
        "3905": "YU",
        "3906": "HAO"
    },
    "Art1Name": {
        "0": "",
        "3000": "WU1",
        "3001": "MO1",
        "3002": "LIN1",
        "3003": "AI1",
        "3004": "MENG1",
        "3005": "WEI1",
        "3006": "YI1",
        "3007": "MING1",
        "3008": "MIN1",
        "3009": "XI1",
        "3901": "MU1",
        "3902": "ZHU1",
        "3903": "DENG1",
        "3904": "SHOU1",
        "3905": "YU1",
        "3906": "HAO1"
    },
    "Art2Name": {
        "0": "",
        "3000": "WU2",
        "3001": "MO2",
        "3002": "LIN2",
        "3003": "AI2",
        "3004": "MENG2",
        "3005": "WEI2",
        "3006": "YI2",
        "3007": "MING2",
        "3008": "MIN2",
        "3009": "XI2",
        "3901": "MU2",
        "3902": "ZHU2",
        "3903": "DENG2",
        "3904": "SHOU2",
        "3905": "YU2",
        "3906": "HAO2"
    },
    "Art3Name": {
        "0": "",
        "3000": "WU3",
        "3001": "MO3",
        "3002": "LIN3",
        "3003": "AI3",
        "3004": "MENG3",
        "3005": "WEI3",
        "3006": "YI3",
        "3007": "MING3",
        "3008": "MIN3",
        "3009": "XI3",
        "3901": "MU3",
        "3902": "ZHU3",
        "3903": "DENG3",
        "3904": "SHOU3",
        "3905": "YU3",
        "3906": "HAO3"
    },
    "StatusName": {
    },
    "EquipName": {
        "0": "NONE",
        "2101": "SWORD",
        "2102": "BOW",
        "2103": "STAFF",
        "2104": "BLADE",
        "2105": "ASSBOW",
        "2106": "DAGGER",
        "2107": "WAND",
        "2108": "SHIELD",
        "2109": "CLAYMORE",
        "2110": "SPEAR",
        "2201": "GLOVES",
        "2202": "BRACELET",
        "2203": "VULTURE",
        "2204": "RING",
        "2205": "DEVOUR",
        "2301": "PLATE",
        "2302": "LEATHER",
        "2303": "CLOTH",
        "2304": "CLOAK",
        "2305": "THORN",
        "2306": "WOOD",
        "2307": "CAPE",
        "2401": "SCARF",
        "2402": "TIARA",
        "2403": "RIBBON"
    },
    "EquipDesc": {
        "0": "NONE",
        "2101": "SWORD",
        "2102": "BOW",
        "2103": "STAFF",
        "2104": "BLADE",
        "2105": "ASSBOW",
        "2106": "DAGGER",
        "2107": "WAND",
        "2108": "SHIELD",
        "2109": "CLAYMORE",
        "2110": "SPEAR",
        "2201": "GLOVES",
        "2202": "BRACELET",
        "2203": "VULTURE",
        "2204": "RING",
        "2205": "DEVOUR",
        "2301": "PLATE",
        "2302": "LEATHER",
        "2303": "CLOTH",
        "2304": "CLOAK",
        "2305": "THORN",
        "2306": "WOOD",
        "2307": "CAPE",
        "2401": "SCARF",
        "2402": "TIARA",
        "2403": "RIBBON"
    },
    "EquipMyst": {
        "0": "[MYST]",
        "2101": "[MYST]",
        "2102": "[MYST]",
        "2103": "[MYST]",
        "2104": "[MYST]",
        "2105": "[MYST]",
        "2106": "[MYST]",
        "2107": "[MYST]",
        "2108": "[MYST]",
        "2109": "[MYST]",
        "2110": "[MYST]",
        "2201": "[MYST]",
        "2202": "[MYST]",
        "2203": "[MYST]",
        "2204": "[MYST]",
        "2205": "[MYST]",
        "2301": "[MYST]",
        "2302": "[MYST]",
        "2303": "[MYST]",
        "2304": "[MYST]",
        "2305": "[MYST]",
        "2306": "[MYST]",
        "2307": "[MYST]",
        "2401": "[MYST]",
        "2402": "[MYST]",
        "2403": "[MYST]"
    },
    "EquipAttrName": {
    },
    "EquipRankName": {
    },
    "AuraName" : {
        "101": "SHI",
        "102": "XIN",
        "103": "FENG",
        "104": "TIAO",
        "105": "YA",
        "201": "BI",
        "202": "MO",
        "203": "DUN",
        "204": "XUE",
        "205": "XIAO",
        "206": "SHENG",
        "207": "E",
        "301": "SHANG",
        "302": "SHEN",
        "303": "CI",
        "304": "REN",
        "305": "RE",
        "306": "DIAN",
        "307": "WU",
        "308": "ZHI",
        "401": "FEI",
        "402": "BO",
        "403": "JU",
        "404": "HONG",
        "405": "JUE",
        "406": "HOU",
        "407": "DUNH",
        "408": "ZI",
        "901": "DI"
    },
    "AuraDesc": {
        "101": "SHI",
        "102": "XIN",
        "103": "FENG",
        "104": "TIAO",
        "105": "YA",
        "201": "BI",
        "202": "MO",
        "203": "DUN",
        "204": "XUE",
        "205": "XIAO",
        "206": "SHENG",
        "207": "E",
        "301": "SHANG",
        "302": "SHEN",
        "303": "CI",
        "304": "REN",
        "305": "RE",
        "306": "DIAN",
        "307": "WU",
        "308": "ZHI",
        "401": "FEI",
        "402": "BO",
        "403": "JU",
        "404": "HONG",
        "405": "JUE",
        "406": "HOU",
        "407": "DUNH",
        "408": "ZI",
        "901": "DI"
    }
}