const gMsgEuJson = 
{
    "Name": "English",
    "MetaData": {
        "Title": "fygemu",
        "Keywords": "",
        "Description": ""
    },
    "PanelName": {
        "fygRank": "Rank",
        "fygLevel": "Level",
        "fygCoin1": "Coin1",
        "fygCoin2": "Coin2",
        "fygCoin3": "Coin3",
        "fygPk": "Fight",
        "fygEquip": "Equip",
        "fygWish": "Wish",
        "fygBeach": "Beach",
        "fygGift": "Gift",
        "fygShop": "Shop",
        "fygLogout": "Logout",
        "fygIndex": "Changes",
        "fygByebye": "Byebye",
        "Rank": "Rank",
        "Prog": "Progress",
        "Fuel": "Stamina",
        "Recover": "Refill Stamina to 100",
        "RecoverA": "Confirm (Cost ",
        "RecoverB": " Coins)",
        "NpcStr": "NPC Strength",
        "PkBattle": "Battle Emulation",
        "PkLoader": "Battle Log",
        "PkButton1": "Search for Resources",
        "PkButton2": "Attack Monsters",
        "PkButton3": "Snatch Progress",
        "Config": "Battle Settings",
        "Output": "Battle Logs",
        "Card": "Card Settings",
        "Equip": "Gear Settings",
        "Aura": "Aura Settings",
        "Wish": "Wish Settings",
        "Amulet": "Amulet Settings",
        "Stats": "Stats",
        "Status": "Status",
        "Require": "",
        "Point": "Points",
        "Import": "Import",
        "Export": "Export",
        "Create": "Create",
        "Editor": "Editor",
        "Remove": "Remove",
        "Confirm": "Confirm",
        "Close": "Close",
        "Manual": "Manual"
    },
    "PanelDesc": {
        "PkBattle": "Starts battle with current configuration.",
        "PkLoader": "Loads battle log from a external file.",
        "PkButton1": "Consumes 10 stamina and 3% progress. The reward range is based on the current rank.",
        "PkButton2": "Consumes consumes 5 stamina. Gains 6% progress on victory, losses 1% on failure.",
        "PkButton3": "Consumes 5 stamina. Gains 12% progress on victory, losses 6% on failure.",
        "PKWinner": " wins!",
        "PKRoundOver": "Round over",
        "ManPowerP": "Physical Power",
        "ManPowerM": "Magical Power",
        "ManPowerA": "Absolute Power",
        "ManDamageH": "Health Damage",
        "ManDamageS": "Shield Damage",
        "ManRecoverH": "Health Recover",
        "ManRecoverS": "Shield Recover",
        "Manual": ""
    },
    "AttrName": {
        "mName": "Name",
        "mActor": "Role",
        "mLevel": "Level",
        "mQuality": "Q",
        "mGrowth": "G",
        "mSkill": "S",
        "mPoint": "P",
        "mStr": "STR",
        "mAgi": "AGI",
        "mInt": "INT",
        "mVit": "VIT",
        "mSpr": "SPR",
        "mMnd": "MND",
        "mAmulStr": "STR",
        "mAmulAgi": "AGI",
        "mAmulInt": "INT",
        "mAmulVit": "VIT",
        "mAmulSpr": "SPR",
        "mAmulMnd": "MND",
        "mAmulPowP": "PATK",
        "mAmulPowM": "MATK",
        "mAmulSpd": "SPD",
        "mAmulRec": "REC",
        "mAmulHp": "HP",
        "mAmulSd": "SD",
        "mAmulLch": "LCH",
        "mAmulRfl": "RFL",
        "mAmulCrt": "CRT",
        "mAmulSkl": "SKL",
        "mAmulDefP": "PDEF",
        "mAmulDefM": "MDEF",
        "mHpPot": "Life Potion",
        "mSdPot": "Shield Potion",
        "mAura101": "101+",
        "mAura102": "102+",
        "mAura103": "103+",
        "mPowBuf": "PVE Pow+",
        "mLifeBuf": "PVE Life+",
        "nHpRat": "Max Health Ratio",
        "nHpMax": "Max Health",
        "nHpHealRat": "Health Recover Ratio",
        "nHpHealFix": "Health Recover",
        "nSdRat": "Max Shield Ratio",
        "nSdMax": "Max Shield",
        "nSdHealRat": "Shield Recover Ratio",
        "nSdHealFix": "Shield Recover",
        "nRecRat": "Recover Ratio",
        "nPowRatP": "Physical Power Ratio",
        "nPowRatM": "Magical Power Ratio",
        "nPowP": "Physical Power",
        "nPowM": "Magical Power",
        "nPowA": "Absolute Power",
        "nSpdRat": "Power Speed Ratio",
        "nSpd": "Power Speed",
        "nAtkRatP": "Physical Attack Ratio",
        "nAtkRatM": "Magical Attack Ratio",
        "nAtkRatC": "Critical Attack Ratio",
        "nAtkAddP": "Physical Attack",
        "nAtkAddM": "Magical Attack",
        "nAtkAddC": "Critical Attack",
        "nDefRatP": "Physical Defense Ratio",
        "nDefRatM": "Magical Defense Ratio",
        "nDefP": "Physical Defense",
        "nDefM": "Magical Defense",
        "nSklRat": "Skill Activation Rate",
        "nCrtRat": "Critical Hit Rate",
        "nEvaRat": "Skill Evade Rate",
        "nDodRat": "Critical Dodge Rate",
        "nSklAdd": "Skill Activation",
        "nCrtAdd": "Critical Hit",
        "nEvaAdd": "Skill Evade",
        "nDodAdd": "Critical Dodge",
        "nResP": "Physical Damage Reduce",
        "nResM": "Magical Damage Reduce",
        "nLchRat": "Life Steal",
        "nRflRat": "Damage Reflection"
    },
    "AttrInfo": {
        "mIsPVE": "Enemy",
        "mHpMax": "HP",
        "mSdMax": "SD",
        "mSpd": "SPD",
        "mPowP": "PA",
        "mPowM": "MA",
        "mDefP": "PD",
        "mDefM": "MD"
    },
    "ActUIInfo": {
        "Crt": "CRT",
        "Rfl": "RFL",
        "Equip2202": "MCRT",
        "Art3008": ["-P", "-M", "-A"],
        "HpPot": "PotH",
        "SdPot": "PotS",
        "StatusPrefix": " ",
        "StatusSuffix": "",
        "SkillPrefix": "",
        "SkillSuffix": "",
        "AuraPrefix": "",
        "AuraSuffix": ""
    },
    "ActorName": {
        "0": "NONE",
        "3000": "WU",
        "3001": "MO",
        "3002": "LIN",
        "3003": "AI",
        "3004": "MENG",
        "3005": "WEI",
        "3006": "YI",
        "3007": "MING",
        "3008": "MIN",
        "3009": "XI",
        "3901": "MU",
        "3902": "ZHU",
        "3903": "DENG",
        "3904": "SHOU",
        "3905": "YU",
        "3906": "HAO"
    },
    "Art1Name": {
        "0": "",
        "3000": "WU1",
        "3001": "MO1",
        "3002": "LIN1",
        "3003": "AI1",
        "3004": "MENG1",
        "3005": "WEI1",
        "3006": "YI1",
        "3007": "MING1",
        "3008": "MIN1",
        "3009": "XI1",
        "3901": "MU1",
        "3902": "ZHU1",
        "3903": "DENG1",
        "3904": "SHOU1",
        "3905": "YU1",
        "3906": "HAO1"
    },
    "Art2Name": {
        "0": "",
        "3000": "WU2",
        "3001": "MO2",
        "3002": "LIN2",
        "3003": "AI2",
        "3004": "MENG2",
        "3005": "WEI2",
        "3006": "YI2",
        "3007": "MING2",
        "3008": "MIN2",
        "3009": "XI2",
        "3901": "MU2",
        "3902": "ZHU2",
        "3903": "DENG2",
        "3904": "SHOU2",
        "3905": "YU2",
        "3906": "HAO2"
    },
    "Art3Name": {
        "0": "",
        "3000": "WU3",
        "3001": "MO3",
        "3002": "LIN3",
        "3003": "AI3",
        "3004": "MENG3",
        "3005": "WEI3",
        "3006": "YI3",
        "3007": "MING3",
        "3008": "MIN3",
        "3009": "XI3",
        "3901": "MU3",
        "3902": "ZHU3",
        "3903": "DENG3",
        "3904": "SHOU3",
        "3905": "YU3",
        "3906": "HAO3"
    },
    "StatusName": {
        "HpRecRat": "Health Recover",
        "SdRecRat": "Shield Recover",
        "PowRatP": "Physical Power Ratio",
        "PowRatM": "Magical Power Ratio",
        "AtkRatP": "Physical Attack Ratio",
        "AtkRatM": "Magical Attack Ratio",
        "AtkRatC": "Critical Attack Ratio",
        "AtkFixP": "Physical Attack Base",
        "AtkFixM": "Magical Attack Base",
        "AtkFixC": "Critical Attack Base",
        "DefRatP": "Physical Defense Ratio",
        "DefRatM": "Magical Defense Ratio",
        "DefFixP": "Physical Defense Base",
        "DefFixM": "Magical Defense Base",
        "SpdRat": "Speed Ratio",
        "SklRat": "Skill Ratio",
        "CrtRat": "Critical Ratio",
        "EvaRat": "Evade Ratio",
        "DodRat": "Dodge Ratio",
        "LchRat": "Leech Ratio",
        "RflRat": "Reflect Ratio",
        "Undead": "Undead",
        "Flare": "Flare",
        "Light": "Light",
        "Dodge": "Dodge",
        "Sight": "Precognition",
        "Mirror": "Mirror"
    },
    "EquipName": {
        "0": "NONE",
        "2101": "SWORD",
        "2102": "BOW",
        "2103": "STAFF",
        "2104": "BLADE",
        "2105": "ASSBOW",
        "2106": "DAGGER",
        "2107": "WAND",
        "2108": "SHIELD",
        "2109": "CLAYMORE",
        "2110": "SPEAR",
        "2201": "GLOVES",
        "2202": "BRACELET",
        "2203": "VULTURE",
        "2204": "RING",
        "2205": "DEVOUR",
        "2301": "PLATE",
        "2302": "LEATHER",
        "2303": "CLOTH",
        "2304": "CLOAK",
        "2305": "THORN",
        "2306": "WOOD",
        "2307": "CAPE",
        "2401": "SCARF",
        "2402": "TIARA",
        "2403": "RIBBON"
    },
    "EquipDesc": {
        "0": "NONE",
        "2101": "SWORD",
        "2102": "BOW",
        "2103": "STAFF",
        "2104": "BLADE",
        "2105": "ASSBOW",
        "2106": "DAGGER",
        "2107": "WAND",
        "2108": "SHIELD",
        "2109": "CLAYMORE",
        "2110": "SPEAR",
        "2201": "GLOVES",
        "2202": "BRACELET",
        "2203": "VULTURE",
        "2204": "RING",
        "2205": "DEVOUR",
        "2301": "PLATE",
        "2302": "LEATHER",
        "2303": "CLOTH",
        "2304": "CLOAK",
        "2305": "THORN",
        "2306": "WOOD",
        "2307": "CAPE",
        "2401": "SCARF",
        "2402": "TIARA",
        "2403": "RIBBON"
    },
    "EquipMyst": {
        "0": "[Mystery]",
        "2101": "[Mystery]",
        "2102": "[Mystery]",
        "2103": "[Mystery]",
        "2104": "[Mystery]",
        "2105": "[Mystery]",
        "2106": "[Mystery]",
        "2107": "[Mystery]",
        "2108": "[Mystery]",
        "2109": "[Mystery]",
        "2110": "[Mystery]",
        "2201": "[Mystery]",
        "2202": "[Mystery]",
        "2203": "[Mystery]",
        "2204": "[Mystery]",
        "2205": "[Mystery]",
        "2301": "[Mystery]",
        "2302": "[Mystery]",
        "2303": "[Mystery]",
        "2304": "[Mystery]",
        "2305": "[Mystery]",
        "2306": "[Mystery]",
        "2307": "[Mystery]",
        "2401": "[Mystery]",
        "2402": "[Mystery]",
        "2403": "[Mystery]"
    },
    "EquipAttrName": {
        "": "",
        "nHpMaxMul": "Max Health %",
        "nHpMaxAdd": "Max Health +",
        "nHpMaxAddStr": "Max Health STR +",
        "nHpHealRat": "Health Recover %",
        "nHpHealAdd": "Health Recover +",
        "nSdMaxMul": "Max Shield %",
        "nSdMaxAdd": "Max Shield +",
        "nSdHealRat": "Shield Recover %",
        "nSdHealAdd": "Shield Recover +",
        "nPowMulP": "Physical Power %",
        "nPowAddP": "Physical Power +",
        "nPowMulM": "Magical Power %",
        "nPowAddM": "Magical Power +",
        "nSpdMul": "Power Speed %",
        "nSpdAdd": "Power Speed +",
        "nAtkRatP": "Physical Attack Ratio +",
        "nAtkAddP": "Physical Attack +",
        "nAtkRatM": "Magical Attack Ratio +",
        "nAtkAddM": "Magical Attack +",
        "nAtkRatC": "Critical Attack Ratio +",
        "nAtkAddC": "Critical Attack +",
        "nSklAdd": "Skill Rate +",
        "nCrtAdd": "Critical Rate +",
        "nEvaAdd": "Skill Evade +",
        "nDodAdd": "Critical Dodge +",
        "nDefRatP": "Physical Defense Ratio +",
        "nDefAddP": "Physical Defense +",
        "nDefRatM": "Magical Defense Ratio +",
        "nDefAddM": "Magical Defense +",
        "nResAddP": "Physical Damage Reduce +",
        "nResAddM": "Magical Damage Reduce +",
        "nLchRat": "Life Steal Ratio +",
        "nRflRat": "Damage Reflection Ratio +"
    },
    "EquipRankName": {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5"
    },
    "AuraName" : {
        "101": "SHI",
        "102": "XIN",
        "103": "FENG",
        "104": "TIAO",
        "105": "YA",
        "201": "BI",
        "202": "MO",
        "203": "DUN",
        "204": "XUE",
        "205": "XIAO",
        "206": "SHENG",
        "207": "E",
        "301": "SHANG",
        "302": "SHEN",
        "303": "CI",
        "304": "REN",
        "305": "RE",
        "306": "DIAN",
        "307": "WU",
        "308": "ZHI",
        "401": "FEI",
        "402": "BO",
        "403": "JU",
        "404": "HONG",
        "405": "JUE",
        "406": "HOU",
        "407": "DUNH",
        "408": "ZI",
        "901": "DI"
    },
    "AuraDesc": {
        "101": "SHI",
        "102": "XIN",
        "103": "FENG",
        "104": "TIAO",
        "105": "YA",
        "201": "BI",
        "202": "MO",
        "203": "DUN",
        "204": "XUE",
        "205": "XIAO",
        "206": "SHENG",
        "207": "E",
        "301": "SHANG",
        "302": "SHEN",
        "303": "CI",
        "304": "REN",
        "305": "RE",
        "306": "DIAN",
        "307": "WU",
        "308": "ZHI",
        "401": "FEI",
        "402": "BO",
        "403": "JU",
        "404": "HONG",
        "405": "JUE",
        "406": "HOU",
        "407": "DUNH",
        "408": "ZI",
        "901": "DI"
    }
}